/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.social.postMeta'

export { $nsid }

/** Metadata associated with a Para post. */
type Main = {
  $type: 'com.para.social.postMeta'
  post: l.AtUriString
  postType: 'policy' | 'matter' | 'meme'
  official?: boolean
  party?: string
  community?: string
  category?: string
  tags?: string[]
  flairs?: string[]
  voteScore: number
  createdAt: l.DatetimeString
}

export type { Main }

/** Metadata associated with a Para post. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    post: l.string({ format: 'at-uri' }),
    postType: l.enum(['policy', 'matter', 'meme']),
    official: l.optional(l.withDefault(l.boolean(), false)),
    party: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    community: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    category: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    tags: l.optional(
      l.array(l.string({ maxLength: 64, maxGraphemes: 64 }), { maxLength: 16 }),
    ),
    flairs: l.optional(
      l.array(l.string({ maxLength: 64, maxGraphemes: 64 }), { maxLength: 16 }),
    ),
    voteScore: l.integer(),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
