/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.highlight.defs'

export { $nsid }

type HighlightView = {
  $type?: 'com.para.highlight.defs#highlightView'
  uri: l.AtUriString
  cid: l.Cid
  creator: l.DidString
  indexedAt: l.DatetimeString
  subjectUri: l.AtUriString
  subjectCid?: string
  text: string
  start: number
  end: number
  color: string
  tag?: string
  community?: string
  state?: string
  party?: string
  visibility: 'public' | 'private' | l.UnknownString
  createdAt: l.DatetimeString
}

export type { HighlightView }

const highlightView = l.typedObject<HighlightView>(
  $nsid,
  'highlightView',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.cid(),
    creator: l.string({ format: 'did' }),
    indexedAt: l.string({ format: 'datetime' }),
    subjectUri: l.string({ format: 'at-uri' }),
    subjectCid: l.optional(l.string()),
    text: l.string({ maxLength: 2000 }),
    start: l.integer({ minimum: 0 }),
    end: l.integer({ minimum: 0 }),
    color: l.string({ maxLength: 32 }),
    tag: l.optional(l.string({ maxLength: 128 })),
    community: l.optional(l.string({ maxLength: 100 })),
    state: l.optional(l.string({ maxLength: 100 })),
    party: l.optional(l.string({ maxLength: 100 })),
    visibility: l.string<{ knownValues: ['public', 'private'] }>(),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { highlightView }
