/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.discourse.getSentiment'

export { $nsid }

/** Get the sentiment breakdown for a community. */
const main = l.query(
  $nsid,
  l.params({
    community: l.optional(l.string()),
    timeframe: l.enum(['1h', '24h', '7d', '30d']),
  }),
  l.jsonPayload({
    sentiment: l.ref<SentimentDistribution>(
      (() => sentimentDistribution) as any,
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type SentimentDistribution = {
  $type?: 'com.para.discourse.getSentiment#sentimentDistribution'

  /**
   * Scaled 0-100
   */
  anger: number

  /**
   * Scaled 0-100
   */
  fear: number

  /**
   * Scaled 0-100
   */
  trust: number

  /**
   * Scaled 0-100
   */
  uncertainty: number

  /**
   * Scaled 0-100
   */
  neutral: number
}

export type { SentimentDistribution }

const sentimentDistribution = l.typedObject<SentimentDistribution>(
  $nsid,
  'sentimentDistribution',
  l.object({
    anger: l.integer(),
    fear: l.integer(),
    trust: l.integer(),
    uncertainty: l.integer(),
    neutral: l.integer(),
  }),
)

export { sentimentDistribution }
