/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.discourse.getTopics'

export { $nsid }

/** Get emergent topic clusters for a community. */
const main = l.query(
  $nsid,
  l.params({
    community: l.optional(l.string()),
    timeframe: l.enum(['1h', '24h', '7d', '30d']),
  }),
  l.jsonPayload({ topics: l.array(l.ref<Topic>((() => topic) as any)) }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type Topic = {
  $type?: 'com.para.discourse.getTopics#topic'
  clusterLabel: string
  keywords?: string
  postCount: number
  authorCount: number

  /**
   * Scaled 0-100
   */
  avgSentiment?: number
}

export type { Topic }

const topic = l.typedObject<Topic>(
  $nsid,
  'topic',
  l.object({
    clusterLabel: l.string(),
    keywords: l.optional(l.string()),
    postCount: l.integer(),
    authorCount: l.integer(),
    avgSentiment: l.optional(l.integer()),
  }),
)

export { topic }
