/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CommunityDefs from './defs.defs.js'

const $nsid = 'com.para.community.getGovernance'

export { $nsid }

/** Get governance roster and role hierarchy for a Para community. */
const main = l.query(
  $nsid,
  l.params({
    community: l.string({ maxLength: 64, maxGraphemes: 64 }),
    communityId: l.optional(l.string({ maxLength: 128, maxGraphemes: 128 })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 200 }), 50),
    ),
  }),
  l.jsonPayload({
    source: l.string<{ knownValues: ['network', 'repo', 'mock'] }>(),
    community: l.string(),
    communityId: l.optional(l.string()),
    slug: l.string(),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.string({ format: 'datetime' }),
    moderators: l.array(
      l.ref<CommunityDefs.ModeratorView>(
        (() => CommunityDefs.moderatorView) as any,
      ),
    ),
    officials: l.array(
      l.ref<CommunityDefs.OfficialView>(
        (() => CommunityDefs.officialView) as any,
      ),
    ),
    deputies: l.array(
      l.ref<CommunityDefs.DeputyRoleView>(
        (() => CommunityDefs.deputyRoleView) as any,
      ),
    ),
    metadata: l.optional(
      l.ref<CommunityDefs.Metadata>((() => CommunityDefs.metadata) as any),
    ),
    editHistory: l.array(
      l.ref<CommunityDefs.HistoryEntry>(
        (() => CommunityDefs.historyEntry) as any,
      ),
    ),
    counters: l.ref<CommunityDefs.Summary>(
      (() => CommunityDefs.summary) as any,
    ),
    summary: l.ref<CommunityDefs.Summary>((() => CommunityDefs.summary) as any),
    computedAt: l.string({ format: 'datetime' }),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
