/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'app.bsky.unspecced.getTaggedSuggestions'

export { $nsid }

/** Get a list of suggestions (feeds and users) tagged with categories */
const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    suggestions: l.array(l.ref<Suggestion>((() => suggestion) as any)),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type Suggestion = {
  $type?: 'app.bsky.unspecced.getTaggedSuggestions#suggestion'
  tag: string
  subjectType: 'actor' | 'feed' | l.UnknownString
  subject: l.UriString
}

export type { Suggestion }

const suggestion = l.typedObject<Suggestion>(
  $nsid,
  'suggestion',
  l.object({
    tag: l.string(),
    subjectType: l.string<{ knownValues: ['actor', 'feed'] }>(),
    subject: l.string({ format: 'uri' }),
  }),
)

export { suggestion }
