/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.actor.defs'

export { $nsid }

/** Aggregated Para profile statistics. */
type ProfileStats = {
  $type?: 'com.para.actor.defs#profileStats'

  /**
   * All-time influence score (Para equivalent of cumulative karma).
   */
  influence: number

  /**
   * Total support received by this actor's Para posts across all time.
   */
  votesReceivedAllTime: number

  /**
   * Total votes/interactions cast by this actor across all time.
   */
  votesCastAllTime: number
  contributions: Contributions

  /**
   * Top communities where this actor contributes.
   */
  activeIn: string[]

  /**
   * Timestamp of the last stats computation.
   */
  computedAt: l.DatetimeString
}

export type { ProfileStats }

/** Aggregated Para profile statistics. */
const profileStats = l.typedObject<ProfileStats>(
  $nsid,
  'profileStats',
  l.object({
    influence: l.integer(),
    votesReceivedAllTime: l.integer(),
    votesCastAllTime: l.integer(),
    contributions: l.ref<Contributions>((() => contributions) as any),
    activeIn: l.array(l.string({ maxLength: 64, maxGraphemes: 64 })),
    computedAt: l.string({ format: 'datetime' }),
  }),
)

export { profileStats }

/** All-time contribution counters. */
type Contributions = {
  $type?: 'com.para.actor.defs#contributions'
  policies: number
  matters: number
  comments: number
}

export type { Contributions }

/** All-time contribution counters. */
const contributions = l.typedObject<Contributions>(
  $nsid,
  'contributions',
  l.object({
    policies: l.integer(),
    matters: l.integer(),
    comments: l.integer(),
  }),
)

export { contributions }

/** Resolved Para account status view. */
type StatusView = {
  $type?: 'com.para.actor.defs#statusView'
  status: string
  party?: string
  community?: string
  createdAt: l.DatetimeString
}

export type { StatusView }

/** Resolved Para account status view. */
const statusView = l.typedObject<StatusView>(
  $nsid,
  'statusView',
  l.object({
    status: l.string({ maxLength: 300, maxGraphemes: 300 }),
    party: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    community: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { statusView }
