/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.community.defs'

export { $nsid }

type Summary = {
  $type?: 'com.para.community.defs#summary'
  members: number
  visiblePosters: number
  policyPosts: number
  matterPosts: number
  badgeHolders: number
}

export type { Summary }

const summary = l.typedObject<Summary>(
  $nsid,
  'summary',
  l.object({
    members: l.integer(),
    visiblePosters: l.integer(),
    policyPosts: l.integer(),
    matterPosts: l.integer(),
    badgeHolders: l.integer(),
  }),
)

export { summary }

type Person = {
  $type?: 'com.para.community.defs#person'
  did?: l.DidString
  handle?: l.HandleString
  displayName?: string
  avatar?: l.UriString
}

export type { Person }

const person = l.typedObject<Person>(
  $nsid,
  'person',
  l.object({
    did: l.optional(l.string({ format: 'did' })),
    handle: l.optional(l.string({ format: 'handle' })),
    displayName: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    avatar: l.optional(l.string({ format: 'uri' })),
  }),
)

export { person }

type ModeratorView = {
  $type?: 'com.para.community.defs#moderatorView'
  did?: l.DidString
  handle?: l.HandleString
  displayName?: string
  avatar?: l.UriString
  role: string
  badge: string
  capabilities: string[]
}

export type { ModeratorView }

const moderatorView = l.typedObject<ModeratorView>(
  $nsid,
  'moderatorView',
  l.object({
    did: l.optional(l.string({ format: 'did' })),
    handle: l.optional(l.string({ format: 'handle' })),
    displayName: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    avatar: l.optional(l.string({ format: 'uri' })),
    role: l.string({ maxGraphemes: 64, maxLength: 64 }),
    badge: l.string({ maxGraphemes: 64, maxLength: 64 }),
    capabilities: l.array(l.string({ maxGraphemes: 64, maxLength: 128 })),
  }),
)

export { moderatorView }

type OfficialView = {
  $type?: 'com.para.community.defs#officialView'
  did?: l.DidString
  handle?: l.HandleString
  displayName?: string
  avatar?: l.UriString
  office: string
  mandate: string
}

export type { OfficialView }

const officialView = l.typedObject<OfficialView>(
  $nsid,
  'officialView',
  l.object({
    did: l.optional(l.string({ format: 'did' })),
    handle: l.optional(l.string({ format: 'handle' })),
    displayName: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    avatar: l.optional(l.string({ format: 'uri' })),
    office: l.string({ maxGraphemes: 64, maxLength: 64 }),
    mandate: l.string({ maxGraphemes: 200, maxLength: 1000 }),
  }),
)

export { officialView }

type Applicant = {
  $type?: 'com.para.community.defs#applicant'
  did?: l.DidString
  handle?: l.HandleString
  displayName?: string
  avatar?: l.UriString
  appliedAt: l.DatetimeString
  status: 'applied' | 'approved' | 'rejected' | l.UnknownString
  note?: string
}

export type { Applicant }

const applicant = l.typedObject<Applicant>(
  $nsid,
  'applicant',
  l.object({
    did: l.optional(l.string({ format: 'did' })),
    handle: l.optional(l.string({ format: 'handle' })),
    displayName: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    avatar: l.optional(l.string({ format: 'uri' })),
    appliedAt: l.string({ format: 'datetime' }),
    status: l.string<{ knownValues: ['applied', 'approved', 'rejected'] }>(),
    note: l.optional(l.string({ maxGraphemes: 200, maxLength: 1000 })),
  }),
)

export { applicant }

type DeputyRoleView = {
  $type?: 'com.para.community.defs#deputyRoleView'
  key: string
  tier: string
  role: string
  description: string
  capabilities: string[]
  activeHolder?: Person
  activeSince?: l.DatetimeString
  votes: number
  applicants: Applicant[]
}

export type { DeputyRoleView }

const deputyRoleView = l.typedObject<DeputyRoleView>(
  $nsid,
  'deputyRoleView',
  l.object({
    key: l.string({ maxGraphemes: 128, maxLength: 128 }),
    tier: l.string({ maxGraphemes: 32, maxLength: 32 }),
    role: l.string({ maxGraphemes: 64, maxLength: 64 }),
    description: l.string({ maxGraphemes: 300, maxLength: 2000 }),
    capabilities: l.array(l.string({ maxGraphemes: 64, maxLength: 128 })),
    activeHolder: l.optional(l.ref<Person>((() => person) as any)),
    activeSince: l.optional(l.string({ format: 'datetime' })),
    votes: l.integer(),
    applicants: l.array(l.ref<Applicant>((() => applicant) as any)),
  }),
)

export { deputyRoleView }

type Metadata = {
  $type?: 'com.para.community.defs#metadata'
  termLengthDays?: number
  reviewCadence?: string
  escalationPath?: string
  publicContact?: string
  lastPublishedAt?: l.DatetimeString
  state?: string
  matterFlairIds?: string[]
  policyFlairIds?: string[]
}

export type { Metadata }

const metadata = l.typedObject<Metadata>(
  $nsid,
  'metadata',
  l.object({
    termLengthDays: l.optional(l.integer()),
    reviewCadence: l.optional(l.string({ maxGraphemes: 128, maxLength: 256 })),
    escalationPath: l.optional(l.string({ maxGraphemes: 128, maxLength: 256 })),
    publicContact: l.optional(l.string({ maxGraphemes: 128, maxLength: 256 })),
    lastPublishedAt: l.optional(l.string({ format: 'datetime' })),
    state: l.optional(l.string({ maxGraphemes: 64, maxLength: 128 })),
    matterFlairIds: l.optional(
      l.array(l.string({ maxGraphemes: 128, maxLength: 128 })),
    ),
    policyFlairIds: l.optional(
      l.array(l.string({ maxGraphemes: 128, maxLength: 128 })),
    ),
  }),
)

export { metadata }

type HistoryEntry = {
  $type?: 'com.para.community.defs#historyEntry'
  id: string
  action: string
  actorDid?: l.DidString
  actorHandle?: l.HandleString
  createdAt: l.DatetimeString
  summary: string
}

export type { HistoryEntry }

const historyEntry = l.typedObject<HistoryEntry>(
  $nsid,
  'historyEntry',
  l.object({
    id: l.string({ maxGraphemes: 128, maxLength: 128 }),
    action: l.string({ maxGraphemes: 128, maxLength: 128 }),
    actorDid: l.optional(l.string({ format: 'did' })),
    actorHandle: l.optional(l.string({ format: 'handle' })),
    createdAt: l.string({ format: 'datetime' }),
    summary: l.string({ maxGraphemes: 300, maxLength: 2000 }),
  }),
)

export { historyEntry }
