/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as UnspeccedDefs from './defs.defs.js'

const $nsid = 'app.bsky.unspecced.getAgeAssuranceState'

export { $nsid }

/** Returns the current state of the age assurance process for an account. This is used to check if the user has completed age assurance or if further action is required. */
const main = l.query(
  $nsid,
  l.params(),
  l.payload(
    'application/json',
    l.ref<UnspeccedDefs.AgeAssuranceState>(
      (() => UnspeccedDefs.ageAssuranceState) as any,
    ),
  ),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
