/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.highlight.annotation'

export { $nsid }

/** A public or private highlight annotation over a post or record. */
type Main = {
  $type: 'com.para.highlight.annotation'
  subjectUri: l.AtUriString

  /**
   * Optional CID of the highlighted record at creation time.
   */
  subjectCid?: string
  text: string
  start: number
  end: number
  color: string
  tag?: string
  community?: string
  state?: string
  party?: string
  visibility: 'public' | 'private' | l.UnknownString
  createdAt: l.DatetimeString
}

export type { Main }

/** A public or private highlight annotation over a post or record. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subjectUri: l.string({ format: 'at-uri' }),
    subjectCid: l.optional(l.string()),
    text: l.string({ maxLength: 2000 }),
    start: l.integer({ minimum: 0 }),
    end: l.integer({ minimum: 0 }),
    color: l.string({ maxLength: 32 }),
    tag: l.optional(l.string({ maxLength: 128 })),
    community: l.optional(l.string({ maxLength: 100 })),
    state: l.optional(l.string({ maxLength: 100 })),
    party: l.optional(l.string({ maxLength: 100 })),
    visibility: l.string<{ knownValues: ['public', 'private'] }>(),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
