/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as HighlightDefs from './defs.defs.js'

const $nsid = 'com.para.highlight.listHighlights'

export { $nsid }

/** List indexed public highlight annotations with optional filters. */
const main = l.query(
  $nsid,
  l.params({
    community: l.optional(l.string({ maxLength: 100 })),
    state: l.optional(l.string({ maxLength: 100 })),
    subject: l.optional(l.string({ format: 'at-uri' })),
    creator: l.optional(l.string({ format: 'did' })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 30),
    ),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    cursor: l.optional(l.string()),
    highlights: l.array(
      l.ref<HighlightDefs.HighlightView>(
        (() => HighlightDefs.highlightView) as any,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
