/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.civic.defs'

export { $nsid }

type CabildeoOption = {
  $type?: 'com.para.civic.defs#cabildeoOption'
  label: string
  description?: string
  isConsensus?: boolean
}

export type { CabildeoOption }

const cabildeoOption = l.typedObject<CabildeoOption>(
  $nsid,
  'cabildeoOption',
  l.object({
    label: l.string({ maxLength: 100 }),
    description: l.optional(l.string({ maxLength: 500 })),
    isConsensus: l.optional(l.boolean()),
  }),
)

export { cabildeoOption }

type OptionSummary = {
  $type?: 'com.para.civic.defs#optionSummary'
  optionIndex: number
  label: string
  votes: number
  positions: number
}

export type { OptionSummary }

const optionSummary = l.typedObject<OptionSummary>(
  $nsid,
  'optionSummary',
  l.object({
    optionIndex: l.integer({ minimum: 0 }),
    label: l.string({ maxLength: 100 }),
    votes: l.integer({ minimum: 0 }),
    positions: l.integer({ minimum: 0 }),
  }),
)

export { optionSummary }

type PositionCounts = {
  $type?: 'com.para.civic.defs#positionCounts'
  total: number
  for: number
  against: number
  amendment: number
  byOption: OptionSummary[]
}

export type { PositionCounts }

const positionCounts = l.typedObject<PositionCounts>(
  $nsid,
  'positionCounts',
  l.object({
    total: l.integer({ minimum: 0 }),
    for: l.integer({ minimum: 0 }),
    against: l.integer({ minimum: 0 }),
    amendment: l.integer({ minimum: 0 }),
    byOption: l.array(l.ref<OptionSummary>((() => optionSummary) as any)),
  }),
)

export { positionCounts }

type VoteTotals = {
  $type?: 'com.para.civic.defs#voteTotals'
  total: number
  direct: number
  delegated: number
}

export type { VoteTotals }

const voteTotals = l.typedObject<VoteTotals>(
  $nsid,
  'voteTotals',
  l.object({
    total: l.integer({ minimum: 0 }),
    direct: l.integer({ minimum: 0 }),
    delegated: l.integer({ minimum: 0 }),
  }),
)

export { voteTotals }

type OutcomeSummary = {
  $type?: 'com.para.civic.defs#outcomeSummary'
  winningOption?: number
  totalParticipants: number
  effectiveTotalPower: number
  tie: boolean
  breakdown: OptionSummary[]
}

export type { OutcomeSummary }

const outcomeSummary = l.typedObject<OutcomeSummary>(
  $nsid,
  'outcomeSummary',
  l.object({
    winningOption: l.optional(l.integer({ minimum: 0 })),
    totalParticipants: l.integer({ minimum: 0 }),
    effectiveTotalPower: l.integer({ minimum: 0 }),
    tie: l.boolean(),
    breakdown: l.array(l.ref<OptionSummary>((() => optionSummary) as any)),
  }),
)

export { outcomeSummary }

type ViewerContext = {
  $type?: 'com.para.civic.defs#viewerContext'
  currentVoteOption?: number
  currentVoteIsDirect?: boolean
  activeDelegation?: l.DidString
  delegateHasVoted?: boolean
  delegatedVoteOption?: number
  delegatedVotedAt?: l.DatetimeString
  gracePeriodEndsAt?: l.DatetimeString
  delegateVoteDismissed?: boolean
}

export type { ViewerContext }

const viewerContext = l.typedObject<ViewerContext>(
  $nsid,
  'viewerContext',
  l.object({
    currentVoteOption: l.optional(l.integer({ minimum: 0 })),
    currentVoteIsDirect: l.optional(l.boolean()),
    activeDelegation: l.optional(l.string({ format: 'did' })),
    delegateHasVoted: l.optional(l.boolean()),
    delegatedVoteOption: l.optional(l.integer({ minimum: 0 })),
    delegatedVotedAt: l.optional(l.string({ format: 'datetime' })),
    gracePeriodEndsAt: l.optional(l.string({ format: 'datetime' })),
    delegateVoteDismissed: l.optional(l.boolean()),
  }),
)

export { viewerContext }

type CabildeoView = {
  $type?: 'com.para.civic.defs#cabildeoView'
  uri: l.AtUriString
  cid: l.Cid
  creator: l.DidString
  indexedAt: l.DatetimeString
  title: string
  description: string
  community: string
  communities?: string[]
  flairs?: string[]
  region?: string
  geoRestricted?: boolean
  options: CabildeoOption[]
  minQuorum?: number
  phase:
    | 'draft'
    | 'open'
    | 'deliberating'
    | 'voting'
    | 'resolved'
    | l.UnknownString
  phaseDeadline?: l.DatetimeString
  createdAt: l.DatetimeString
  optionSummary: OptionSummary[]
  positionCounts: PositionCounts
  voteTotals: VoteTotals
  outcomeSummary?: OutcomeSummary
  viewerContext?: ViewerContext
}

export type { CabildeoView }

const cabildeoView = l.typedObject<CabildeoView>(
  $nsid,
  'cabildeoView',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.cid(),
    creator: l.string({ format: 'did' }),
    indexedAt: l.string({ format: 'datetime' }),
    title: l.string({ maxLength: 300 }),
    description: l.string({ maxLength: 30000 }),
    community: l.string({ maxLength: 100 }),
    communities: l.optional(
      l.array(l.string({ maxLength: 100 }), { maxLength: 10 }),
    ),
    flairs: l.optional(
      l.array(l.string({ maxLength: 100 }), { maxLength: 10 }),
    ),
    region: l.optional(l.string({ maxLength: 100 })),
    geoRestricted: l.optional(l.boolean()),
    options: l.array(l.ref<CabildeoOption>((() => cabildeoOption) as any), {
      maxLength: 10,
    }),
    minQuorum: l.optional(l.integer({ minimum: 1 })),
    phase: l.string<{
      knownValues: ['draft', 'open', 'deliberating', 'voting', 'resolved']
    }>(),
    phaseDeadline: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.string({ format: 'datetime' }),
    optionSummary: l.array(l.ref<OptionSummary>((() => optionSummary) as any)),
    positionCounts: l.ref<PositionCounts>((() => positionCounts) as any),
    voteTotals: l.ref<VoteTotals>((() => voteTotals) as any),
    outcomeSummary: l.optional(
      l.ref<OutcomeSummary>((() => outcomeSummary) as any),
    ),
    viewerContext: l.optional(
      l.ref<ViewerContext>((() => viewerContext) as any),
    ),
  }),
)

export { cabildeoView }

type PositionView = {
  $type?: 'com.para.civic.defs#positionView'
  uri: l.AtUriString
  cid: l.Cid
  creator: l.DidString
  indexedAt: l.DatetimeString
  cabildeo: l.AtUriString
  stance: 'for' | 'against' | 'amendment' | l.UnknownString
  optionIndex?: number
  text: string
  compassQuadrant?: string
  createdAt: l.DatetimeString
}

export type { PositionView }

const positionView = l.typedObject<PositionView>(
  $nsid,
  'positionView',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.cid(),
    creator: l.string({ format: 'did' }),
    indexedAt: l.string({ format: 'datetime' }),
    cabildeo: l.string({ format: 'at-uri' }),
    stance: l.string<{ knownValues: ['for', 'against', 'amendment'] }>(),
    optionIndex: l.optional(l.integer({ minimum: 0 })),
    text: l.string({ maxLength: 3000 }),
    compassQuadrant: l.optional(l.string({ maxLength: 100 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { positionView }
