/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.civic.position'

export { $nsid }

/** User's structured debate stance on a Cabildeo. */
type Main = {
  $type: 'com.para.civic.position'
  cabildeo: l.AtUriString
  stance: 'for' | 'against' | 'amendment' | l.UnknownString
  optionIndex?: number
  text: string
  compassQuadrant?: string
  createdAt: l.DatetimeString
}

export type { Main }

/** User's structured debate stance on a Cabildeo. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    cabildeo: l.string({ format: 'at-uri' }),
    stance: l.string<{ knownValues: ['for', 'against', 'amendment'] }>(),
    optionIndex: l.optional(l.integer({ minimum: 0 })),
    text: l.string({ maxLength: 3000 }),
    compassQuadrant: l.optional(l.string({ maxLength: 100 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
