/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as FeedGetAuthorFeed from './getAuthorFeed.defs.js'

const $nsid = 'com.para.feed.getPosts'

export { $nsid }

/** Get Para post views for a specified list of post AT-URIs. */
const main = l.query(
  $nsid,
  l.params({
    uris: l.array(l.string({ format: 'at-uri' }), { maxLength: 25 }),
  }),
  l.jsonPayload({
    posts: l.array(
      l.ref<FeedGetAuthorFeed.PostView>(
        (() => FeedGetAuthorFeed.postView) as any,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
