/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.status'

export { $nsid }

/** Current public status for a Para account. */
type Main = {
  $type: 'com.para.status'

  /**
   * User's public status message.
   */
  status: string

  /**
   * Optional political party affiliation.
   */
  party?: string

  /**
   * Optional primary community label.
   */
  community?: string
  createdAt: l.DatetimeString
}

export type { Main }

/** Current public status for a Para account. */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    status: l.string({ maxLength: 300, maxGraphemes: 300 }),
    party: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    community: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
