/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.civic.cabildeo'

export { $nsid }

/** A structured civic deliberation proposal. */
type Main = {
  $type: 'com.para.civic.cabildeo'
  title: string
  description: string
  community: string
  communities?: string[]
  flairs?: string[]
  region?: string
  geoRestricted?: boolean
  options: CabildeoOption[]
  minQuorum?: number
  phase:
    | 'draft'
    | 'open'
    | 'deliberating'
    | 'voting'
    | 'resolved'
    | l.UnknownString
  phaseDeadline?: l.DatetimeString
  createdAt?: l.DatetimeString
}

export type { Main }

/** A structured civic deliberation proposal. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 300 }),
    description: l.string({ maxLength: 30000 }),
    community: l.string({ maxLength: 100 }),
    communities: l.optional(
      l.array(l.string({ maxLength: 100 }), { maxLength: 10 }),
    ),
    flairs: l.optional(
      l.array(l.string({ maxLength: 100 }), { maxLength: 10 }),
    ),
    region: l.optional(l.string({ maxLength: 100 })),
    geoRestricted: l.optional(l.boolean()),
    options: l.array(l.ref<CabildeoOption>((() => cabildeoOption) as any), {
      maxLength: 10,
    }),
    minQuorum: l.optional(l.integer({ minimum: 1 })),
    phase: l.string<{
      knownValues: ['draft', 'open', 'deliberating', 'voting', 'resolved']
    }>(),
    phaseDeadline: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type CabildeoOption = {
  $type?: 'com.para.civic.cabildeo#cabildeoOption'
  label: string
  description?: string
}

export type { CabildeoOption }

const cabildeoOption = l.typedObject<CabildeoOption>(
  $nsid,
  'cabildeoOption',
  l.object({
    label: l.string({ maxLength: 100 }),
    description: l.optional(l.string({ maxLength: 500 })),
  }),
)

export { cabildeoOption }
