/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CivicDefs from './defs.defs.js'

const $nsid = 'com.para.civic.listCabildeoPositions'

export { $nsid }

/** List indexed positions for a Cabildeo with optional stance filter. */
const main = l.query(
  $nsid,
  l.params({
    cabildeo: l.string({ format: 'at-uri' }),
    stance: l.optional(
      l.string<{ knownValues: ['for', 'against', 'amendment'] }>(),
    ),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    cursor: l.optional(l.string()),
    positions: l.array(
      l.ref<CivicDefs.PositionView>((() => CivicDefs.positionView) as any),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
