/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.community.listBoards'

export { $nsid }

/** Lists PARA community boards available to the viewer, along with creation capability. */
const main = l.query(
  $nsid,
  l.params({
    query: l.optional(l.string({ maxGraphemes: 128, maxLength: 256 })),
    state: l.optional(l.string({ maxGraphemes: 64, maxLength: 128 })),
    participationKind: l.optional(
      l.string<{ knownValues: ['matter', 'policy'] }>(),
    ),
    flairId: l.optional(l.string({ maxGraphemes: 128, maxLength: 128 })),
    sort: l.optional(
      l.withDefault(
        l.string<{ knownValues: ['recent', 'activity', 'size'] }>(),
        'recent',
      ),
    ),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.payload('application/json', l.ref<Output>((() => output) as any)),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type BoardView = {
  $type?: 'com.para.community.listBoards#boardView'
  uri: l.AtUriString
  cid: l.CidString
  creatorDid: l.DidString
  creatorHandle?: l.HandleString
  creatorDisplayName?: string
  communityId: string
  slug: string
  name: string
  description?: string
  quadrant: string
  delegatesChatId: string
  subdelegatesChatId: string
  memberCount: number
  viewerMembershipState:
    | 'none'
    | 'pending'
    | 'active'
    | 'left'
    | 'removed'
    | 'blocked'
    | l.UnknownString
  viewerRoles?: string[]
  status?: 'draft' | 'active' | l.UnknownString
  founderStarterPackUri?: l.AtUriString
  createdAt: l.DatetimeString
}

export type { BoardView }

const boardView = l.typedObject<BoardView>(
  $nsid,
  'boardView',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.string({ format: 'cid' }),
    creatorDid: l.string({ format: 'did' }),
    creatorHandle: l.optional(l.string({ format: 'handle' })),
    creatorDisplayName: l.optional(
      l.string({ maxGraphemes: 64, maxLength: 640 }),
    ),
    communityId: l.string({ maxGraphemes: 128, maxLength: 256 }),
    slug: l.string({ maxGraphemes: 128, maxLength: 256 }),
    name: l.string({ maxGraphemes: 128, maxLength: 256 }),
    description: l.optional(l.string({ maxGraphemes: 300, maxLength: 3000 })),
    quadrant: l.string({ maxGraphemes: 64, maxLength: 128 }),
    delegatesChatId: l.string(),
    subdelegatesChatId: l.string(),
    memberCount: l.integer(),
    viewerMembershipState: l.string<{
      knownValues: ['none', 'pending', 'active', 'left', 'removed', 'blocked']
    }>(),
    viewerRoles: l.optional(
      l.array(l.string({ maxGraphemes: 64, maxLength: 128 })),
    ),
    status: l.optional(l.string<{ knownValues: ['draft', 'active'] }>()),
    founderStarterPackUri: l.optional(l.string({ format: 'at-uri' })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { boardView }

type Output = {
  $type?: 'com.para.community.listBoards#output'
  boards: BoardView[]
  cursor?: string
  canCreateCommunity: boolean
}

export type { Output }

const output = l.typedObject<Output>(
  $nsid,
  'output',
  l.object({
    boards: l.array(l.ref<BoardView>((() => boardView) as any)),
    cursor: l.optional(l.string()),
    canCreateCommunity: l.boolean(),
  }),
)

export { output }
