/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as FeedGetAuthorFeed from './getAuthorFeed.defs.js'

const $nsid = 'com.para.feed.getPostThread'

export { $nsid }

/** Get a Para post thread around a post URI. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.string({ format: 'at-uri' }),
    depth: l.optional(
      l.withDefault(l.integer({ minimum: 0, maximum: 1000 }), 6),
    ),
    parentHeight: l.optional(
      l.withDefault(l.integer({ minimum: 0, maximum: 1000 }), 80),
    ),
  }),
  l.jsonPayload({
    post: l.ref<FeedGetAuthorFeed.PostView>(
      (() => FeedGetAuthorFeed.postView) as any,
    ),
    parents: l.array(
      l.ref<FeedGetAuthorFeed.PostView>(
        (() => FeedGetAuthorFeed.postView) as any,
      ),
    ),
    replies: l.array(
      l.ref<FeedGetAuthorFeed.PostView>(
        (() => FeedGetAuthorFeed.postView) as any,
      ),
    ),
  }),
  ['NotFound'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
