/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.social.getPostMeta'

export { $nsid }

/** Get Para social metadata for a post. */
const main = l.query(
  $nsid,
  l.params({ post: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    postType: l.optional(l.enum(['policy', 'matter', 'meme'])),
    official: l.optional(l.boolean()),
    party: l.optional(l.string()),
    community: l.optional(l.string()),
    category: l.optional(l.string()),
    tags: l.optional(l.array(l.string())),
    flairs: l.optional(l.array(l.string())),
    voteScore: l.integer(),
    interactionMode: l.enum(['policy_ballot', 'reddit_votes']),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
  ['NotFound'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
