// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.actor.getProfileStats

package para

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ActorGetProfileStats_Output is the output of a com.para.actor.getProfileStats call.
type ActorGetProfileStats_Output struct {
	Actor  string                  `json:"actor" cborgen:"actor"`
	Stats  *ActorDefs_ProfileStats `json:"stats" cborgen:"stats"`
	Status *ActorDefs_StatusView   `json:"status,omitempty" cborgen:"status,omitempty"`
}

// ActorGetProfileStats calls the XRPC method "com.para.actor.getProfileStats".
//
// actor: Handle or DID of the actor.
func ActorGetProfileStats(ctx context.Context, c lexutil.LexClient, actor string) (*ActorGetProfileStats_Output, error) {
	var out ActorGetProfileStats_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if err := c.LexDo(ctx, lexutil.Query, "", "com.para.actor.getProfileStats", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
