// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.actor.defs

package para

// ActorDefs_Contributions is a "contributions" in the com.para.actor.defs schema.
//
// All-time contribution counters.
type ActorDefs_Contributions struct {
	Comments int64 `json:"comments" cborgen:"comments"`
	Matters  int64 `json:"matters" cborgen:"matters"`
	Policies int64 `json:"policies" cborgen:"policies"`
}

// ActorDefs_ProfileStats is a "profileStats" in the com.para.actor.defs schema.
//
// Aggregated Para profile statistics.
type ActorDefs_ProfileStats struct {
	// activeIn: Top communities where this actor contributes.
	ActiveIn []string `json:"activeIn" cborgen:"activeIn"`
	// computedAt: Timestamp of the last stats computation.
	ComputedAt    string                   `json:"computedAt" cborgen:"computedAt"`
	Contributions *ActorDefs_Contributions `json:"contributions" cborgen:"contributions"`
	// influence: All-time influence score (Para equivalent of cumulative karma).
	Influence int64 `json:"influence" cborgen:"influence"`
	// votesCastAllTime: Total votes/interactions cast by this actor across all time.
	VotesCastAllTime int64 `json:"votesCastAllTime" cborgen:"votesCastAllTime"`
	// votesReceivedAllTime: Total support received by this actor's Para posts across all time.
	VotesReceivedAllTime int64 `json:"votesReceivedAllTime" cborgen:"votesReceivedAllTime"`
}

// ActorDefs_StatusView is a "statusView" in the com.para.actor.defs schema.
//
// Resolved Para account status view.
type ActorDefs_StatusView struct {
	Community *string `json:"community,omitempty" cborgen:"community,omitempty"`
	CreatedAt string  `json:"createdAt" cborgen:"createdAt"`
	Party     *string `json:"party,omitempty" cborgen:"party,omitempty"`
	Status    string  `json:"status" cborgen:"status"`
}
