// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.civic.vote

package para

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("com.para.civic.vote", &CivicVote{})
}

type CivicVote struct {
	LexiconTypeID  string   `json:"$type" cborgen:"$type,const=com.para.civic.vote"`
	Cabildeo       string   `json:"cabildeo" cborgen:"cabildeo"`
	CreatedAt      string   `json:"createdAt" cborgen:"createdAt"`
	DelegatedFrom  []string `json:"delegatedFrom,omitempty" cborgen:"delegatedFrom,omitempty"`
	IsDirect       bool     `json:"isDirect" cborgen:"isDirect"`
	SelectedOption int64    `json:"selectedOption" cborgen:"selectedOption"`
}
