// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.civic.delegation

package para

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("com.para.civic.delegation", &CivicDelegation{})
}

type CivicDelegation struct {
	LexiconTypeID string   `json:"$type" cborgen:"$type,const=com.para.civic.delegation"`
	Cabildeo      *string  `json:"cabildeo,omitempty" cborgen:"cabildeo,omitempty"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	DelegateTo    string   `json:"delegateTo" cborgen:"delegateTo"`
	Reason        *string  `json:"reason,omitempty" cborgen:"reason,omitempty"`
	ScopeFlairs   []string `json:"scopeFlairs,omitempty" cborgen:"scopeFlairs,omitempty"`
}
