// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.civic.cabildeo

package para

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("com.para.civic.cabildeo", &CivicCabildeo{})
}

type CivicCabildeo struct {
	LexiconTypeID string                          `json:"$type" cborgen:"$type,const=com.para.civic.cabildeo"`
	Communities   []string                        `json:"communities,omitempty" cborgen:"communities,omitempty"`
	Community     string                          `json:"community" cborgen:"community"`
	CreatedAt     *string                         `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Description   string                          `json:"description" cborgen:"description"`
	Flairs        []string                        `json:"flairs,omitempty" cborgen:"flairs,omitempty"`
	GeoRestricted *bool                           `json:"geoRestricted,omitempty" cborgen:"geoRestricted,omitempty"`
	MinQuorum     *int64                          `json:"minQuorum,omitempty" cborgen:"minQuorum,omitempty"`
	Options       []*CivicCabildeo_CabildeoOption `json:"options" cborgen:"options"`
	Phase         string                          `json:"phase" cborgen:"phase"`
	PhaseDeadline *string                         `json:"phaseDeadline,omitempty" cborgen:"phaseDeadline,omitempty"`
	Region        *string                         `json:"region,omitempty" cborgen:"region,omitempty"`
	Title         string                          `json:"title" cborgen:"title"`
}

// CivicCabildeo_CabildeoOption is a "cabildeoOption" in the com.para.civic.cabildeo schema.
type CivicCabildeo_CabildeoOption struct {
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	Label       string  `json:"label" cborgen:"label"`
}
