// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.civic.position

package para

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("com.para.civic.position", &CivicPosition{})
}

type CivicPosition struct {
	LexiconTypeID   string  `json:"$type" cborgen:"$type,const=com.para.civic.position"`
	Cabildeo        string  `json:"cabildeo" cborgen:"cabildeo"`
	CompassQuadrant *string `json:"compassQuadrant,omitempty" cborgen:"compassQuadrant,omitempty"`
	CreatedAt       string  `json:"createdAt" cborgen:"createdAt"`
	OptionIndex     *int64  `json:"optionIndex,omitempty" cborgen:"optionIndex,omitempty"`
	Stance          string  `json:"stance" cborgen:"stance"`
	Text            string  `json:"text" cborgen:"text"`
}
