// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.feed.getAuthorFeed

package para

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedGetAuthorFeed_Output is the output of a com.para.feed.getAuthorFeed call.
type FeedGetAuthorFeed_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Feed   []*FeedGetAuthorFeed_PostView `json:"feed" cborgen:"feed"`
}

// FeedGetAuthorFeed_PostView is a "postView" in the com.para.feed.getAuthorFeed schema.
type FeedGetAuthorFeed_PostView struct {
	Author      string   `json:"author" cborgen:"author"`
	Cid         string   `json:"cid" cborgen:"cid"`
	CreatedAt   string   `json:"createdAt" cborgen:"createdAt"`
	Flairs      []string `json:"flairs,omitempty" cborgen:"flairs,omitempty"`
	Langs       []string `json:"langs,omitempty" cborgen:"langs,omitempty"`
	PostType    *string  `json:"postType,omitempty" cborgen:"postType,omitempty"`
	ReplyParent *string  `json:"replyParent,omitempty" cborgen:"replyParent,omitempty"`
	ReplyRoot   *string  `json:"replyRoot,omitempty" cborgen:"replyRoot,omitempty"`
	Tags        []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	Text        string   `json:"text" cborgen:"text"`
	Uri         string   `json:"uri" cborgen:"uri"`
}

// FeedGetAuthorFeed calls the XRPC method "com.para.feed.getAuthorFeed".
//
// actor: Handle or DID of the actor.
func FeedGetAuthorFeed(ctx context.Context, c lexutil.LexClient, actor string, cursor string, limit int64) (*FeedGetAuthorFeed_Output, error) {
	var out FeedGetAuthorFeed_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "com.para.feed.getAuthorFeed", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
