// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.feed.getPostThread

package para

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedGetPostThread_Output is the output of a com.para.feed.getPostThread call.
type FeedGetPostThread_Output struct {
	Parents []*FeedGetAuthorFeed_PostView `json:"parents" cborgen:"parents"`
	Post    *FeedGetAuthorFeed_PostView   `json:"post" cborgen:"post"`
	Replies []*FeedGetAuthorFeed_PostView `json:"replies" cborgen:"replies"`
}

// FeedGetPostThread calls the XRPC method "com.para.feed.getPostThread".
//
// depth: How many levels of reply depth to include.
// parentHeight: How many levels of parent posts to include.
// uri: Reference (AT-URI) to the post record.
func FeedGetPostThread(ctx context.Context, c lexutil.LexClient, depth int64, parentHeight int64, uri string) (*FeedGetPostThread_Output, error) {
	var out FeedGetPostThread_Output

	params := map[string]interface{}{}
	if depth != 0 {
		params["depth"] = depth
	}
	if parentHeight != 0 {
		params["parentHeight"] = parentHeight
	}
	params["uri"] = uri
	if err := c.LexDo(ctx, lexutil.Query, "", "com.para.feed.getPostThread", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
