// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.feed.getPosts

package para

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedGetPosts_Output is the output of a com.para.feed.getPosts call.
type FeedGetPosts_Output struct {
	Posts []*FeedGetAuthorFeed_PostView `json:"posts" cborgen:"posts"`
}

// FeedGetPosts calls the XRPC method "com.para.feed.getPosts".
//
// uris: List of Para post AT-URIs to return.
func FeedGetPosts(ctx context.Context, c lexutil.LexClient, uris []string) (*FeedGetPosts_Output, error) {
	var out FeedGetPosts_Output

	params := map[string]interface{}{}
	params["uris"] = uris
	if err := c.LexDo(ctx, lexutil.Query, "", "com.para.feed.getPosts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
