// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.post

package para

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	comatproto "github.com/bluesky-social/indigo/api/atproto"
	appbsky "github.com/bluesky-social/indigo/api/bsky"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	lexutil.RegisterType("com.para.post", &Post{})
}

type Post struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=com.para.post"`
	// createdAt: Client-declared timestamp when this post was originally created.
	CreatedAt string      `json:"createdAt" cborgen:"createdAt"`
	Embed     *Post_Embed `json:"embed,omitempty" cborgen:"embed,omitempty"`
	// entities: DEPRECATED: replaced by app.bsky.richtext.facet.
	Entities []*Post_Entity `json:"entities,omitempty" cborgen:"entities,omitempty"`
	// facets: Annotations of text (mentions, URLs, hashtags, etc)
	Facets []*appbsky.RichtextFacet `json:"facets,omitempty" cborgen:"facets,omitempty"`
	// flairs: Optional para-specific flairs associated with the post.
	Flairs []string `json:"flairs,omitempty" cborgen:"flairs,omitempty"`
	// labels: Self-label values for this post. Effectively content warnings.
	Labels *Post_Labels `json:"labels,omitempty" cborgen:"labels,omitempty"`
	// langs: Indicates human language of post primary text content.
	Langs []string `json:"langs,omitempty" cborgen:"langs,omitempty"`
	// postType: Optional para-specific post type (policy, matter, meme, etc).
	PostType *string        `json:"postType,omitempty" cborgen:"postType,omitempty"`
	Reply    *Post_ReplyRef `json:"reply,omitempty" cborgen:"reply,omitempty"`
	// tags: Additional hashtags, in addition to any included in post text and facets.
	Tags []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	// text: The primary post content. May be an empty string, if there are embeds.
	Text string `json:"text" cborgen:"text"`
}

type Post_Embed struct {
	EmbedImages          *appbsky.EmbedImages
	EmbedVideo           *appbsky.EmbedVideo
	EmbedExternal        *appbsky.EmbedExternal
	EmbedRecord          *appbsky.EmbedRecord
	EmbedRecordWithMedia *appbsky.EmbedRecordWithMedia
}

func (t *Post_Embed) MarshalJSON() ([]byte, error) {
	if t.EmbedImages != nil {
		t.EmbedImages.LexiconTypeID = "app.bsky.embed.images"
		return json.Marshal(t.EmbedImages)
	}
	if t.EmbedVideo != nil {
		t.EmbedVideo.LexiconTypeID = "app.bsky.embed.video"
		return json.Marshal(t.EmbedVideo)
	}
	if t.EmbedExternal != nil {
		t.EmbedExternal.LexiconTypeID = "app.bsky.embed.external"
		return json.Marshal(t.EmbedExternal)
	}
	if t.EmbedRecord != nil {
		t.EmbedRecord.LexiconTypeID = "app.bsky.embed.record"
		return json.Marshal(t.EmbedRecord)
	}
	if t.EmbedRecordWithMedia != nil {
		t.EmbedRecordWithMedia.LexiconTypeID = "app.bsky.embed.recordWithMedia"
		return json.Marshal(t.EmbedRecordWithMedia)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *Post_Embed) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.images":
		t.EmbedImages = new(appbsky.EmbedImages)
		return json.Unmarshal(b, t.EmbedImages)
	case "app.bsky.embed.video":
		t.EmbedVideo = new(appbsky.EmbedVideo)
		return json.Unmarshal(b, t.EmbedVideo)
	case "app.bsky.embed.external":
		t.EmbedExternal = new(appbsky.EmbedExternal)
		return json.Unmarshal(b, t.EmbedExternal)
	case "app.bsky.embed.record":
		t.EmbedRecord = new(appbsky.EmbedRecord)
		return json.Unmarshal(b, t.EmbedRecord)
	case "app.bsky.embed.recordWithMedia":
		t.EmbedRecordWithMedia = new(appbsky.EmbedRecordWithMedia)
		return json.Unmarshal(b, t.EmbedRecordWithMedia)
	default:
		return nil
	}
}

func (t *Post_Embed) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.EmbedImages != nil {
		return t.EmbedImages.MarshalCBOR(w)
	}
	if t.EmbedVideo != nil {
		return t.EmbedVideo.MarshalCBOR(w)
	}
	if t.EmbedExternal != nil {
		return t.EmbedExternal.MarshalCBOR(w)
	}
	if t.EmbedRecord != nil {
		return t.EmbedRecord.MarshalCBOR(w)
	}
	if t.EmbedRecordWithMedia != nil {
		return t.EmbedRecordWithMedia.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *Post_Embed) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := lexutil.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.images":
		t.EmbedImages = new(appbsky.EmbedImages)
		return t.EmbedImages.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.video":
		t.EmbedVideo = new(appbsky.EmbedVideo)
		return t.EmbedVideo.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.external":
		t.EmbedExternal = new(appbsky.EmbedExternal)
		return t.EmbedExternal.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.record":
		t.EmbedRecord = new(appbsky.EmbedRecord)
		return t.EmbedRecord.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.recordWithMedia":
		t.EmbedRecordWithMedia = new(appbsky.EmbedRecordWithMedia)
		return t.EmbedRecordWithMedia.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// Post_Entity is a "entity" in the com.para.post schema.
//
// Deprecated: use facets instead.
type Post_Entity struct {
	Index *Post_TextSlice `json:"index" cborgen:"index"`
	// type: Expected values are 'mention' and 'link'.
	Type  string `json:"type" cborgen:"type"`
	Value string `json:"value" cborgen:"value"`
}

// Self-label values for this post. Effectively content warnings.
type Post_Labels struct {
	LabelDefs_SelfLabels *comatproto.LabelDefs_SelfLabels
}

func (t *Post_Labels) MarshalJSON() ([]byte, error) {
	if t.LabelDefs_SelfLabels != nil {
		t.LabelDefs_SelfLabels.LexiconTypeID = "com.atproto.label.defs#selfLabels"
		return json.Marshal(t.LabelDefs_SelfLabels)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *Post_Labels) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.atproto.label.defs#selfLabels":
		t.LabelDefs_SelfLabels = new(comatproto.LabelDefs_SelfLabels)
		return json.Unmarshal(b, t.LabelDefs_SelfLabels)
	default:
		return nil
	}
}

func (t *Post_Labels) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.LabelDefs_SelfLabels != nil {
		return t.LabelDefs_SelfLabels.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *Post_Labels) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := lexutil.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "com.atproto.label.defs#selfLabels":
		t.LabelDefs_SelfLabels = new(comatproto.LabelDefs_SelfLabels)
		return t.LabelDefs_SelfLabels.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// Post_ReplyRef is a "replyRef" in the com.para.post schema.
type Post_ReplyRef struct {
	Parent *comatproto.RepoStrongRef `json:"parent" cborgen:"parent"`
	Root   *comatproto.RepoStrongRef `json:"root" cborgen:"root"`
}

// Post_TextSlice is a "textSlice" in the com.para.post schema.
//
// Deprecated. Use app.bsky.richtext instead -- A text segment. Start is inclusive, end is exclusive. Indices are for utf16-encoded strings.
type Post_TextSlice struct {
	End   int64 `json:"end" cborgen:"end"`
	Start int64 `json:"start" cborgen:"start"`
}
