// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.status

package para

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("com.para.status", &Status{})
}

type Status struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=com.para.status"`
	// community: Optional primary community label.
	Community *string `json:"community,omitempty" cborgen:"community,omitempty"`
	CreatedAt string  `json:"createdAt" cborgen:"createdAt"`
	// party: Optional political party affiliation.
	Party *string `json:"party,omitempty" cborgen:"party,omitempty"`
	// status: User's public status message.
	Status string `json:"status" cborgen:"status"`
}
