// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.social.postMeta

package para

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("com.para.social.postMeta", &SocialPostMeta{})
}

type SocialPostMeta struct {
	LexiconTypeID string   `json:"$type" cborgen:"$type,const=com.para.social.postMeta"`
	Category      *string  `json:"category,omitempty" cborgen:"category,omitempty"`
	Community     *string  `json:"community,omitempty" cborgen:"community,omitempty"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	Flairs        []string `json:"flairs,omitempty" cborgen:"flairs,omitempty"`
	Official      *bool    `json:"official,omitempty" cborgen:"official,omitempty"`
	Party         *string  `json:"party,omitempty" cborgen:"party,omitempty"`
	Post          string   `json:"post" cborgen:"post"`
	PostType      string   `json:"postType" cborgen:"postType"`
	Tags          []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	VoteScore     int64    `json:"voteScore" cborgen:"voteScore"`
}
