// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.para.social.getPostMeta

package para

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// SocialGetPostMeta_Output is the output of a com.para.social.getPostMeta call.
type SocialGetPostMeta_Output struct {
	Category        *string  `json:"category,omitempty" cborgen:"category,omitempty"`
	Community       *string  `json:"community,omitempty" cborgen:"community,omitempty"`
	CreatedAt       *string  `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Flairs          []string `json:"flairs,omitempty" cborgen:"flairs,omitempty"`
	InteractionMode string   `json:"interactionMode" cborgen:"interactionMode"`
	Official        *bool    `json:"official,omitempty" cborgen:"official,omitempty"`
	Party           *string  `json:"party,omitempty" cborgen:"party,omitempty"`
	PostType        *string  `json:"postType,omitempty" cborgen:"postType,omitempty"`
	Tags            []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	Uri             string   `json:"uri" cborgen:"uri"`
	VoteScore       int64    `json:"voteScore" cborgen:"voteScore"`
}

// SocialGetPostMeta calls the XRPC method "com.para.social.getPostMeta".
func SocialGetPostMeta(ctx context.Context, c lexutil.LexClient, post string) (*SocialGetPostMeta_Output, error) {
	var out SocialGetPostMeta_Output

	params := map[string]interface{}{}
	params["post"] = post
	if err := c.LexDo(ctx, lexutil.Query, "", "com.para.social.getPostMeta", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
