/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ActorDefs from './defs.defs.js'

const $nsid = 'com.para.actor.getProfileStats'

export { $nsid }

/** Get Para profile stats and current Para status for an actor. */
const main = l.query(
  $nsid,
  l.params({ actor: l.string({ format: 'at-identifier' }) }),
  l.jsonPayload({
    actor: l.string({ format: 'did' }),
    stats: l.ref<ActorDefs.ProfileStats>((() => ActorDefs.profileStats) as any),
    status: l.optional(
      l.ref<ActorDefs.StatusView>((() => ActorDefs.statusView) as any),
    ),
  }),
  ['NotFound', 'BlockedActor', 'BlockedByActor'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
