/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.discourse.getSnapshot'

export { $nsid }

/** Get aggregate discourse metrics for a community. */
const main = l.query(
  $nsid,
  l.params({
    community: l.optional(l.string()),
    timeframe: l.enum(['1h', '24h', '7d', '30d']),
  }),
  l.jsonPayload({
    snapshots: l.array(l.ref<Snapshot>((() => snapshot) as any)),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type Snapshot = {
  $type?: 'com.para.discourse.getSnapshot#snapshot'
  community: string
  bucket: l.DatetimeString
  postCount: number
  uniqueAuthors: number

  /**
   * Scaled 0-100
   */
  avgConstructiveness?: number

  /**
   * Scaled 0-100
   */
  semanticVolatility?: number

  /**
   * Scaled 0-100
   */
  lexicalDiversity?: number

  /**
   * Scaled 0-100
   */
  polarizationDelta?: number

  /**
   * Scaled 0-100
   */
  echoChamberIndex?: number
  topKeywords?: string
  sentimentDistribution?: string
}

export type { Snapshot }

const snapshot = l.typedObject<Snapshot>(
  $nsid,
  'snapshot',
  l.object({
    community: l.string(),
    bucket: l.string({ format: 'datetime' }),
    postCount: l.integer(),
    uniqueAuthors: l.integer(),
    avgConstructiveness: l.optional(l.integer()),
    semanticVolatility: l.optional(l.integer()),
    lexicalDiversity: l.optional(l.integer()),
    polarizationDelta: l.optional(l.integer()),
    echoChamberIndex: l.optional(l.integer()),
    topKeywords: l.optional(l.string()),
    sentimentDistribution: l.optional(l.string()),
  }),
)

export { snapshot }
