/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CivicDefs from './defs.defs.js'

const $nsid = 'com.para.civic.listCabildeos'

export { $nsid }

/** List indexed Cabildeos with aggregate summaries and optional viewer context. */
const main = l.query(
  $nsid,
  l.params({
    community: l.optional(l.string({ maxLength: 100 })),
    phase: l.optional(
      l.string<{
        knownValues: ['draft', 'open', 'deliberating', 'voting', 'resolved']
      }>(),
    ),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 30),
    ),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    cursor: l.optional(l.string()),
    cabildeos: l.array(
      l.ref<CivicDefs.CabildeoView>((() => CivicDefs.cabildeoView) as any),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
