/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.civic.vote'

export { $nsid }

/** The cast vote on a deliberation. */
type Main = {
  $type: 'com.para.civic.vote'
  cabildeo: l.AtUriString
  selectedOption: number
  isDirect: boolean
  delegatedFrom?: l.DidString[]
  createdAt: l.DatetimeString
}

export type { Main }

/** The cast vote on a deliberation. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    cabildeo: l.string({ format: 'at-uri' }),
    selectedOption: l.integer({ minimum: 0 }),
    isDirect: l.boolean(),
    delegatedFrom: l.optional(
      l.array(l.string({ format: 'did' }), { maxLength: 10000 }),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
