name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  app:
    name: App Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build i18n catalogs
        run: yarn intl:build

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: NODE_ENV=test yarn test --forceExit

      - name: Verify lockfile generation
        run: yarn lockfile-lint

      - name: Prettier check
        run: yarn prettier --check .

  bskyweb:
    name: bskyweb Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Create placeholder static assets
        run: |
          mkdir -p bskyweb/static/js bskyweb/static/css bskyweb/static/media
          touch bskyweb/static/js/blah.js
          touch bskyweb/static/css/blah.txt
          touch bskyweb/static/media/blah.txt

      - name: Go check
        run: cd bskyweb && make check

      - name: Go build
        run: cd bskyweb && make build

      - name: Go test
        run: cd bskyweb && make test

      - name: Go lint
        run: cd bskyweb && make lint
